musica = input("Digite a primeira linha de uma música: ")
print(musica)
comprimento = len(musica)
print("O comprimento da linha da música é:", comprimento)
inicio = int(input("Digite o número inicial: "))
fim = int(input("Digite o número final: "))
print("A seção da linha da música é:", musica[inicio:fim])